### ISSUE TITLE
Request to sign nuget package

### ISSUE THREAD

**Issue by marc2982** [tsibelman/aws-signer-v4-dot-net#12]
Hi,

Could you please sign the nuget package? We require strongly-named assemblies in our project.

Thanks!
Marc

**Comment by tsibelman** [comment]
Sorry, but I will not implement this change because of time commitment needed, you free to take my code and make internal dll with it, as you can see its very small amount of code.

**Comment by FantasticFiasco** [comment]
@tsibelman I don't think it would be hard to strong-name the assembly, It's a couple of clicks away in Visual Studio.

@marc2982 If you still require a strong-named assembly, there's always [aws-signature-version-4](https://github.com/FantasticFiasco/aws-signature-version-4). Sorry for the shameless plug.

**Comment by tsibelman** [comment]
I encourage everyone to adapt your version, of this library, at a time I just wanted to release something to open source that could benefit people in my situation, but if something better comes along I can only recommend to use it.

**Comment by tsibelman** [comment]
@FantasticFiasco I read the readme in your repo and was a bit overwhelmed. Don't you think that feeling resentment just because my library exists it a bit strange? I got some stars and thousands of downloads because I solved the annoying issue for others, I didn't recived any benefit from releasing this library and didn't hurt anyone.

**Comment by FantasticFiasco** [comment]
I don't think you should promote anything else than what you have here. After all you have almost 50.000 downloads on nuget.org, and that proves a lot! Many developers have used your library in many situations, and it does its job. I don't think anyone can take that away from you.

My library has 100 downloads, I am not yet confident enough that it will handle all situations, only time will tell. I think you should be proud of what you've accomplished here. You've saved a lot of time for many developers, that is apparent by the number of stars you have on this repo.

Please keep developing for the open source community, we all love you for it.

**Comment by FantasticFiasco** [comment]
> I read the readme in your repo and was a bit overwhelmed.

I am sorry, I was in a bad place when I wrote that piece of text. I'd just been debugging our production that went down because of the stupid sigv4. I'll rewrite it. It was not even your package we used, we wrote our own, but we where heavily inspired by this code, and we failed to see that some steps regarding the headers where wrong.

I'll get right on it to change the readme. Again, I was not angry at you, I was angry at us for not finding the issues before we hit prod.

**Comment by tsibelman** [comment]
No problem, and thank you for compliment you wrote above. If you interested in contributing to this repo I would be happy to make you comaintainer it looks like you did a lot of work.

**Comment by FantasticFiasco** [comment]
I'd love to get @marc2982 sorted out. Would you accept a PR where I add a strong name to your assembly?

**Comment by FantasticFiasco** [comment]
BTW, I've updated my readme. I am no longer hostile to a community of open source contributors that do work with no reward at all. I am thankful for your feedback on my behavior.

**Comment by tsibelman** [comment]
Yes I would accept such PR

**Comment by FantasticFiasco** [comment]
Here you go. I am sure @marc2982 would be willing to try it out before releasing an official version. What do you say Marc, up for the task?

**Comment by tsibelman** [comment]
I published version 0.7.0 that is strongly named
